name: chairs_factory
description: Visual notes application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_fonts: ^2.1.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  skeleton_text: ^3.0.0
  sqflite: ^2.0.1

dev_dependencies:
  flutter_launcher_icons: 
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
